'use strict';

export const httpUrls = {
    LOGIN: 'login',
    COUNTRIES: 'getCountries',
    STATES:'getStatesByCountry',
    ADD_DIRECT_CUSTOMER:'addCustomer',
    UPDATE_DIRECT_CUSTOMER:'updateCustomer',
    DC_ROLES: 'getRoles',
    CSP_ROLES: 'getCSPRoles',
    ADD_CSP_CUSTOMER: 'addCSPCustomer',
    ADD_NEW_CUSTOMER: 'addCustomer',
    UPDATE_CSP_CUSTOMER: 'updateCSPCustomer',
    CREATE_PASSWORD: 'createPassword',
    ADD_CONSENT: 'updateTenantAppInfo',
    GET_CONSENT: 'getTenantAppInfoStatus',
    IS_CONSENT_VERIFIED: 'getIsConsentStatusById',
    VALIDATE_PASSWPORD_TOKEN: 'checkValidToken',
    GET_DC_DATA: 'getListCustomers',
    GET_CSP_DC_DATA: 'getListCustomersCSPAdmin',
    GET_CSP_DATA:'getCSPListCustomers',
    GET_DC_USER_DATA: 'getcustomer',
    GET_CSP_USER_DATA: 'getCSPCustomer',
    GET_CUSTOMER_USER_DATA: 'CustomerAdminGetUser',
    EDIT_PLAYA_USER_DATA: 'adminEditProfile',
    EDIT_CUST_ADMIN_USER_DATA: 'editProfile',
    EDIT_ADMIN_USER_DATA: 'updateCSPAdminProfile',
    DEACTIVATE_CSP_DIRECT_USERS:'removeUserFromCustomer',
    UPDATE_USER_STATUS:'updateStatusCustomer',
    FORGOT_PWD:'forgotPassword',
    REMOVE_SUBSCRIPTION:'removeSubscriptionFromCustomer',
    GET_LOGO:'getProfileImage',
    GET_POWERBI_DATA:'getParamasPowerbi',
    GET_SUBSCRIPTIONS:'CustomerAdminListSubscriptions',
    UPDATE_SUBSCRIPTIONS:'CustomerAdminUpdateSubscriptions',
    TAG_ALL_RESOURCES:'listAllResources',
    TAG_ALL_TAGS:'listAllTags',
    AUTO_COMPLETE_TAGS : 'autoSuggestionTags',
    ADD_TAG : 'addTag',
    REMOVE_TAG : 'removeTag',
    TAG_FILTERS : 'getTagFilters',
    VIEW_TAG_RESOURCES : 'viewTagstoResources',
    UPDATE_TAG_RESOURCES : 'updateTagstoResources',
    GET_RESOURCE_TAGS: 'getResourcesByTag',
    ALERT_FEED: 'getAlertFeeds',
    ALERT_LIST: 'listAllAlerts',
    ALERT_LIST_CATEGORY: 'getAlertListCategories',
    ALERT_LIST_TAGS: 'getAlertListTags',
    ALERT_CONFIG_DATA: 'getAlertConfigData',
    ADD_ALERT: 'addAlert',
    UPDATE_ALERT: 'updateAlert',
    REMOVE_ALERT: 'removeAlert',
    GET_ALERT_BY_ID: 'getAlertInfo',
    ADD_CUSTOMER_ADMIN_USER: 'CustomerAdminAddUser',
    EDIT_CUSTOMER_ADMIN_USER: 'CustomerAdminUpdateUser',
    GET_CUSTOMER_ADMIN_USER_DATA:'CustomerAdminGetListUsers',
    UPDATE_USER_CUST_ADMIN_STATUS:'CustomerAdminUpdateStatusUser'
}

